"""
Investment Screening Agent
--------------------------
Agentic: the model calls both tools (get_news_tool, get_fundamentals_tool)
and synthesises a structured ScreeningOutput for the Portfolio Manager.

Architecture
------------
Two files by design: this module holds all business logic and can be imported
or run standalone. app.py is pure Streamlit UI with no business logic of its own.

Reproducibility
---------------
temperature=0 + pinned model string makes synthesis deterministic: given the
same tool outputs, the model produces the same structured answer.

Two irreducible variability sources remain:
  1. Live news — Tavily returns different articles on every call, so two runs
     on the same company at different times will see different news.
  2. Model sampling at the tool-calling stage — even at temperature=0, the
     model's decisions about which tools to call and in what order are not
     fully pinned.

Every run is persisted to screening_runs.jsonl with the exact tool payloads
the model saw, so any run can be audited or replayed.

Tool compliance
---------------
The agent is instructed via system prompt to call both tools, but this is a
prompt instruction, not a hard constraint. Compliance is verified post-run by
parsing result.all_messages() for ToolCallPart entries filtered to our known
tool names. If compliance fails, screen() still returns — the caller (app.py)
decides how to surface the failure to the PM.

Monitoring (RunMonitor)
-----------------------
llm_requests : number of round-trips to the LLM API in one run. Typically 2:
               first to issue tool calls, second to synthesise from tool outputs.
               1 means the model skipped tools (compliance will fail).
               3 means the model called tools sequentially rather than in
               parallel (an extra round-trip in the middle).
input_tokens : tokens sent TO the model across all requests in one run.
               Resets on every screen() call — does not accumulate.
               Dominated by the tool payloads (news articles + financials JSON)
               that are re-sent in full as part of request 2.
output_tokens: tokens generated BY the model — tool-call instructions plus
               the final structured JSON answer. Small relative to input.

Quality checks (check_quality)
-------------------------------
Company name in news: checks whether the retrieved news articles actually
  mention the target company. Uses three candidates in order:
    1. First two words of the legal name  e.g. "CANADIAN TIRE"
    2. First word of the legal name       e.g. "CANADIAN"
    3. Clean ticker (leading letters only) e.g. "CTC" from "CTC/A"
  Full legal names and raw tickers with exchange suffixes (e.g. "CTC/A CN")
  never appear verbatim in news article text and are therefore not used.
  A warning means none of the candidates appeared in the news payload —
  possible sign the search returned off-topic results.

Verdict
-------
The verdict field (High Priority / Worth Further Review / Low Priority /
Deprioritize) is based on qualitative descriptions in the output schema, not
hard quantitative thresholds. The model weighs revenue growth rate,
gross-margin direction, balance-sheet position, and news tone holistically.
Two runs on identical data could in principle produce different verdicts.
If an auditable, rule-based verdict is needed, the field descriptions should
be replaced with explicit numeric thresholds (e.g. "High Priority if YoY
revenue growth >= 25% AND gross margin stable or expanding").

Gross margin interpretation
---------------------------
Expanding gross margin = positive: pricing power or scale benefits.
Contracting gross margin = negative: competitive pressure or discounting to
grow. A company with 30% revenue growth but falling margins each quarter is
scaling a structurally unprofitable model.

Environment variables (.env)
-----------------------------
  ANTHROPIC_API_KEY  — Anthropic API key
  TAVILY_API_KEY     — tavily.com (free tier: 1 000 searches/month)
  SCREENING_MODEL    — optional, default: anthropic:claude-sonnet-4-6
"""

import json
import os
import re
import sys
from dataclasses import asdict, dataclass, field
from datetime import date, datetime
from pathlib import Path
from typing import Literal

import pandas as pd
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from pydantic_ai import Agent, RunContext
from pydantic_ai.messages import ModelRequest, ModelResponse, ToolCallPart, ToolReturnPart

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

load_dotenv()

# ---------------------------------------------------------------------------
# Dependency container
# ---------------------------------------------------------------------------
@dataclass
class ScreeningDeps:
    companies:   pd.DataFrame
    bal_sheets:  pd.DataFrame
    income_stmt: pd.DataFrame
    tavily_key:  str


def load_deps(data_dir: Path | None = None) -> ScreeningDeps:
    d = data_dir or Path(__file__).parent
    return ScreeningDeps(
        companies   = pd.read_csv(d / "CompanyList.csv"),
        bal_sheets  = pd.read_feather(d / "BalanceSheets.feather"),
        income_stmt = pd.read_feather(d / "IncomeStatements.feather"),
        tavily_key  = os.environ["TAVILY_API_KEY"],
    )


# ---------------------------------------------------------------------------
# Output schema
# ---------------------------------------------------------------------------
class ScreeningOutput(BaseModel):
    verdict: Literal["High Priority", "Worth Further Review", "Low Priority", "Deprioritize"] = Field(
        description=(
            "Top-line signal for the Portfolio Manager. "
            "High Priority: high-conviction growth story with strong financials. "
            "Worth Further Review: solid growth case with manageable risks. "
            "Low Priority: interesting but needs monitoring or more data. "
            "Deprioritize: does not meet growth criteria or risk is too high."
        )
    )
    growth_signal: str = Field(
        description=(
            "Two sentences maximum. State the headline YoY revenue growth rate, "
            "gross-margin direction, and whether this fits a growth mandate. "
            "Plain text only — no markdown, no bullet points, no asterisks."
        )
    )
    news_positives: list[str] = Field(
        description=(
            "Positive signals from recent news. Maximum 4 items. "
            "Each item: one short sentence, plain text, no asterisks."
        )
    )
    news_negatives: list[str] = Field(
        description=(
            "Negative signals or red flags from recent news. Maximum 4 items. "
            "Each item: one short sentence, plain text, no asterisks."
        )
    )
    financial_highlights: str = Field(
        description=(
            "Three sentences maximum covering: revenue trajectory with % YoY, "
            "gross-margin level and trend, and balance-sheet position (net cash or net debt). "
            "Use numbers from the data. Plain text only — no markdown."
        )
    )
    risks: list[str] = Field(
        description=(
            "Key risks for a growth investor. Maximum 4 items. "
            "Each item: one short sentence naming the specific risk. "
            "Plain text only — no asterisks."
        )
    )


# ---------------------------------------------------------------------------
# Per-run monitoring
# ---------------------------------------------------------------------------
@dataclass
class RunMonitor:
    company:             str
    news_called:         bool       = False
    fundamentals_called: bool       = False
    tool_call_sequence:  list[dict] = field(default_factory=list)
    llm_requests:        int        = 0
    input_tokens:        int        = 0
    output_tokens:       int        = 0
    news_raw:            str | None = None

    @property
    def tool_compliance(self) -> str:
        return "Full Input" if (self.news_called and self.fundamentals_called) else "Partial Input"

    def update_from_usage(self, usage) -> None:
        self.llm_requests  = usage.requests      or 0
        self.input_tokens  = usage.input_tokens  or 0
        self.output_tokens = usage.output_tokens or 0


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------
_SYSTEM_PROMPT = """
You are an equity research assistant supporting a Portfolio Manager running a
growth strategy.

Growth investors focus on:
- Revenue growth rate: YoY >= 15% is the threshold for "growth"
- Gross margin level and trend: expansion signals pricing power / scale
- Operating leverage: revenue growing faster than opex is a positive
- Balance sheet: net cash preferred; net debt must be justified by growth
- TAM signals: is the market itself growing, or is this market-share capture?
- Competitive positioning: moat, switching costs, network effects
- Management credibility: guidance track record, tone in recent statements

You have access to two data retrieval tools:
  get_news_tool(ticker) — retrieves current internet news via live search
  get_fundamentals_tool(ticker) — returns balance-sheet and income-statement data

You MUST call BOTH tools before producing your final structured answer.
Do not skip either tool, and do not rely on your own training knowledge
about the company in place of calling the tools.

Output rules:
- Plain text only in every field. No markdown: no **, no *, no #, no bullet dashes.
- Be concise. The PM reads dozens of screens — every sentence must earn its place.
- Cite specific numbers (%, $) from the data rather than vague adjectives.
"""

_model_id = os.getenv("SCREENING_MODEL", "anthropic:claude-sonnet-4-6")

agent = Agent(
    model=_model_id,
    output_type=ScreeningOutput,
    system_prompt=_SYSTEM_PROMPT,
    deps_type=ScreeningDeps,
    defer_model_check=True,
)


@agent.tool
def get_news_tool(ctx: RunContext[ScreeningDeps], ticker: str) -> str:
    """Retrieve current internet news for a company via Tavily search."""
    # Resolve canonical company name from the dataset so the search is never
    # misled by ambiguous tickers (e.g. ADS → Alliance Data vs Adidas).
    mask = ctx.deps.companies["BB_Ticker"].str.contains(ticker, case=False, na=False)
    if not mask.any():
        mask = ctx.deps.companies["Name"].str.contains(ticker, case=False, na=False)
    company_name = (
        ctx.deps.companies[mask].iloc[0]["Name"] if mask.any() else ticker
    )

    from tavily import TavilyClient
    client = TavilyClient(api_key=ctx.deps.tavily_key)
    resp = client.search(
        query=f"{company_name} stock news earnings growth strategy {date.today().year}",
        max_results=5,
        search_depth="basic",
    )
    articles = resp.get("results", [])
    return json.dumps(
        [{"title": a["title"], "content": a["content"][:800], "url": a["url"]}
         for a in articles],
        indent=2,
    )


def get_fundamentals(ticker: str, deps: ScreeningDeps) -> str:
    """Return balance-sheet and income-statement data from local files."""
    mask = deps.companies["BB_Ticker"].str.contains(ticker, case=False, na=False)
    if not mask.any():
        mask = deps.companies["Name"].str.contains(ticker, case=False, na=False)
    if not mask.any():
        return f"No match for '{ticker}'. In-scope: {deps.companies['BB_Ticker'].tolist()}"

    row = deps.companies[mask].iloc[0]
    bb  = row["BB_Ticker"]
    bs  = deps.bal_sheets[deps.bal_sheets["BB_Ticker"] == bb][["index", "2024", "2025"]]
    inc = deps.income_stmt[deps.income_stmt["BB_Ticker"] == bb].drop(
        columns=["index", "BB_Ticker"]
    )
    return json.dumps(
        {
            "company":          row["Name"],
            "ticker":           bb,
            "country":          row["Country"],
            "sector":           row["Sector"],
            "balance_sheet":    bs.to_dict(orient="records"),
            "income_statement": inc.to_dict(orient="records"),
        },
        indent=2,
        default=str,
    )


@agent.tool
def get_fundamentals_tool(ctx: RunContext[ScreeningDeps], ticker: str) -> str:
    """Return balance-sheet and income-statement data from local files."""
    return get_fundamentals(ticker, ctx.deps)


# ---------------------------------------------------------------------------
# Message-history parser
# ---------------------------------------------------------------------------
_AGENT_TOOL_NAMES = {"get_news_tool", "get_fundamentals_tool"}
_TOOL_DISPLAY     = {"get_news_tool": "get_news", "get_fundamentals_tool": "get_fundamentals"}


def _parse_run(messages) -> tuple[bool, bool, list[dict], dict]:
    news_called         = False
    fundamentals_called = False
    call_sequence       = []
    raw_outputs         = {"news": None, "fundamentals": None}
    step                = 0
    llm_turn            = 0   # increments once per ModelResponse that contains tools

    for msg in messages:
        if isinstance(msg, ModelResponse):
            turn_tools = [
                p for p in msg.parts
                if isinstance(p, ToolCallPart) and p.tool_name in _AGENT_TOOL_NAMES
            ]
            if turn_tools:
                llm_turn += 1
                for part in turn_tools:
                    step += 1
                    args = part.args if isinstance(part.args, dict) else {}
                    call_sequence.append({
                        "step":     step,
                        "tool":     _TOOL_DISPLAY[part.tool_name],
                        "args":     args,
                        "llm_turn": llm_turn,   # same value = called in parallel
                    })
                    if part.tool_name == "get_news_tool":
                        news_called = True
                    elif part.tool_name == "get_fundamentals_tool":
                        fundamentals_called = True
        elif isinstance(msg, ModelRequest):
            for part in msg.parts:
                if isinstance(part, ToolReturnPart) and part.tool_name in _AGENT_TOOL_NAMES:
                    content = str(part.content) if not isinstance(part.content, str) else part.content
                    if part.tool_name == "get_news_tool":
                        raw_outputs["news"] = content
                    elif part.tool_name == "get_fundamentals_tool":
                        raw_outputs["fundamentals"] = content

    return news_called, fundamentals_called, call_sequence, raw_outputs


# ---------------------------------------------------------------------------
# Audit log
# ---------------------------------------------------------------------------
_LOG_FILE = Path(__file__).parent / "screening_runs.jsonl"


def _log_run(company, news_raw, fundamentals_raw, output, monitor):
    def _try_parse(s):
        if s is None:
            return None
        try:
            return json.loads(s)
        except (json.JSONDecodeError, ValueError):
            return s

    record = {
        "timestamp":        datetime.utcnow().isoformat() + "Z",
        "company":          company,
        "model":            _model_id,
        "monitor":          asdict(monitor),
        "tool_outputs":     {"news": _try_parse(news_raw), "fundamentals": _try_parse(fundamentals_raw)},
        "screening_output": output.model_dump() if output else None,
    }
    with open(_LOG_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------------
# Quality check
# ---------------------------------------------------------------------------
def check_quality(
    output:           ScreeningOutput,
    fundamentals_raw: str | None,
    news_raw:         str | None = None,
    company:          str | None = None,
) -> dict:
    def extract_floats(text: str) -> list[float]:
        out = []
        for tok in re.findall(r"\d+(?:[,.]\d+)*", text):
            try:
                out.append(float(tok.replace(",", "")))
            except ValueError:
                pass
        return out

    def is_grounded(fig, data_floats, tol=0.01):
        return any(abs(fig - d) / max(abs(d), 1e-9) <= tol for d in data_floats)

    summary_floats = extract_floats(output.financial_highlights)
    data_floats    = extract_floats(fundamentals_raw or "")
    ungrounded     = [f for f in summary_floats if not is_grounded(f, data_floats)]

    # Company relevance: check whether the company is mentioned in the news payload.
    # Candidates (in decreasing specificity):
    #   - first two words of name  e.g. "CANADIAN TIRE"  — specific, commonly used
    #   - first word of name       e.g. "CANADIAN"        — fallback
    #   - clean ticker             e.g. "CTC" from "CTC/A" — often in financial articles
    # Full legal names and raw tickers with exchange suffixes are never in article text.
    company_in_news = None
    if news_raw and company:
        news_lower = news_raw.lower()
        candidates = []
        if fundamentals_raw:
            try:
                full_name = json.loads(fundamentals_raw).get("company", "")
                if full_name:
                    words = full_name.split()
                    candidates.append(" ".join(words[:2]))  # first two words
                    candidates.append(words[0])             # first word
            except (json.JSONDecodeError, AttributeError):
                pass
        # clean ticker: keep only leading letters (drop "/A", exchange codes, etc.)
        clean_ticker = re.match(r"[A-Za-z]+", company)
        if clean_ticker:
            candidates.append(clean_ticker.group())
        company_in_news = any(c.lower() in news_lower for c in candidates if c)

    # Detect missing fundamentals — company is in CompanyList but has no rows
    # in the feather files (e.g. Canadian Tire).
    fundamentals_available = True
    if fundamentals_raw:
        try:
            fund = json.loads(fundamentals_raw)
            fundamentals_available = bool(
                fund.get("balance_sheet") or fund.get("income_statement")
            )
        except (json.JSONDecodeError, AttributeError):
            pass

    return {
        "schema_complete":          True,
        "fundamentals_available":   fundamentals_available,
        "company_in_news":          company_in_news,
        "news_positives_filled":    len(output.news_positives) >= 1,
        "news_negatives_filled":    len(output.news_negatives) >= 1,
        "risks_filled":             len(output.risks) >= 1,
    }


# ---------------------------------------------------------------------------
# Public screening function
# ---------------------------------------------------------------------------
def screen(company: str, deps: ScreeningDeps) -> tuple[ScreeningOutput, RunMonitor, dict]:
    """
    Run one screening and return (output, monitor, quality).

    quality is produced by check_quality() using the tool payloads already
    captured during the run — no second call to get_fundamentals() is needed.
    The company name for the news relevance check is extracted directly from
    the fundamentals payload returned by the agent.
    """
    mon    = RunMonitor(company=company)
    result = agent.run_sync(
        f"Screen this company for a growth equity strategy: {company}",
        deps=deps,
        model_settings={"temperature": 0},
    )
    news_called, fundamentals_called, call_seq, raw_outputs = _parse_run(result.all_messages())
    mon.news_called         = news_called
    mon.fundamentals_called = fundamentals_called
    mon.tool_call_sequence  = call_seq
    mon.news_raw            = raw_outputs.get("news")
    mon.update_from_usage(result.usage)

    fundamentals_raw = raw_outputs.get("fundamentals")
    _log_run(company, mon.news_raw, fundamentals_raw, result.output, mon)

    quality = check_quality(
        output=result.output,
        fundamentals_raw=fundamentals_raw,
        news_raw=mon.news_raw,
        company=company,
    )
    return result.output, mon, quality
